#version 460
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout(binding = 0, rg32f)           uniform image3D prevstaggeredu; /* .x = vel.u, .y = interpolation weight */
layout(binding = 1, rg32f)           uniform image3D prevstaggeredv; /* .x = vel.v, .y = interpolation weight */
layout(binding = 2, rg32f)           uniform image3D prevstaggeredw; /* .x = vel.w, .y = interpolation weight */
layout(binding = 3, rg32f) writeonly uniform image3D nextstaggeredu; /* .x = vel.u, .y = interpolation weight */
layout(binding = 4, rg32f) writeonly uniform image3D nextstaggeredv; /* .x = vel.v, .y = interpolation weight */
layout(binding = 5, rg32f) writeonly uniform image3D nextstaggeredw; /* .x = vel.w, .y = interpolation weight */


uniform float ku_epsilon; 
uniform uint  ku_chooseBndDir;
uniform ivec3 ku_gridsize;


void boundaryCondXDir(ivec3 ijk);
void boundaryCondYDir(ivec3 ijk);
void boundaryCondZDir(ivec3 ijk);
void normalizeVelocities(ivec3 ijk);


void main()
{
    ivec3 texelCoord = ivec3(gl_GlobalInvocationID.xyz);
    switch(ku_chooseBndDir) {
        case 0: boundaryCondXDir(texelCoord); break;
        case 1: boundaryCondYDir(texelCoord); break;
        case 2: boundaryCondZDir(texelCoord); break;
        case 3: normalizeVelocities(texelCoord); break;
        default: break;
    }
    return;
}




/*
    Pseudocode:
    For all j, k in the grid:
        u(0, j, k) = u(1, j, k) = u(nx - 1, j, k) = u(nx, j, k) = 0
        v(0, j, k) = v(1, j, k)
        w(0, j, k) = w(1, j, k)
        v(nx - 1, j, k) = v(nx - 2, j, k)
        w(nx - 1, j, k) = w(nx - 2, j, k)
    For all i, k in the grid:
        v(i, 0, k) = v(i, 1, k) = v(i, ny - 2, k) = v(i, ny - 1, k) = 0
        u(i, 0, k) = u(i, 1, k)
        w(i, 0, k) = w(i, 1, k)
        u(i, ny - 1, k) = u(i, ny - 2, k)
        w(i, ny - 1, k) = w(i, ny - 2, k)
    For all i, j in the grid:
        w(i, j, 0) = w(i, j, 1) = w(i, j, nz - 2) = w(i, j, nz - 1) = 0
        u(i, j, 0) = u(i, j, 1)
        v(i, j, 0) = v(i, j, 1)
        u(i, j, nz - 1) = u(i, j, nz - 2)
        v(i, j, nz - 1) = v(i, j, nz - 2)
*/
void boundaryCondXDir(ivec3 ijk)
{
    ivec3 lowerBounds[2] = ivec3[2](
        ivec3(0, ijk.yz),
        ivec3(1, ijk.yz)
    );
    ivec3 upperBounds[2] = ivec3[2](
        ivec3(ku_gridsize.x - 1, ijk.yz),
        ivec3(ku_gridsize.x - 0, ijk.yz)
    );
    imageStore(nextstaggeredu, lowerBounds[0], vec4(0));
    imageStore(nextstaggeredu, lowerBounds[1], vec4(0));
    imageStore(nextstaggeredu, upperBounds[0], vec4(0));
    imageStore(nextstaggeredu, upperBounds[1], vec4(0));
    imageStore(nextstaggeredv, lowerBounds[0], 
        imageLoad(prevstaggeredv, lowerBounds[1]) 
    );
    imageStore(nextstaggeredw, lowerBounds[0], 
        imageLoad(prevstaggeredw, lowerBounds[1]) 
    );
    upperBounds[0].x -= 1;
    upperBounds[1].x -= 1;
    imageStore(nextstaggeredv, upperBounds[1], 
        imageLoad(prevstaggeredv, upperBounds[0]) 
    );
    imageStore(nextstaggeredw, upperBounds[1], 
        imageLoad(prevstaggeredw, upperBounds[0]) 
    );
    return;
}


void boundaryCondYDir(ivec3 ijk)
{
    ivec3 lowerBounds[2] = ivec3[2](
        ivec3(ijk.x, 0, ijk.z),
        ivec3(ijk.x, 1, ijk.z)
    );
    ivec3 upperBounds[2] = ivec3[2](
        ivec3(ijk.x, ku_gridsize.y - 1, ijk.z),
        ivec3(ijk.x, ku_gridsize.y - 0, ijk.z)
    );
    imageStore(nextstaggeredv,  lowerBounds[0], vec4(0));
    imageStore(nextstaggeredv,  lowerBounds[1], vec4(0));
    imageStore(nextstaggeredv,  upperBounds[0], vec4(0));
    imageStore(nextstaggeredv,  upperBounds[1], vec4(0));
    
    imageStore(nextstaggeredu, lowerBounds[0], 
        imageLoad(prevstaggeredu, lowerBounds[1]) 
    );
    imageStore(nextstaggeredw, lowerBounds[0], 
        imageLoad(prevstaggeredw, lowerBounds[1]) 
    );
    upperBounds[0].y -= 1;
    upperBounds[1].y -= 1;
    imageStore(nextstaggeredu, upperBounds[1], 
        imageLoad(prevstaggeredu, upperBounds[0]) 
    );
    imageStore(nextstaggeredw, upperBounds[1], 
        imageLoad(prevstaggeredw, upperBounds[0]) 
    );
    return;
}


void boundaryCondZDir(ivec3 ijk)
{
    ivec3 lowerBounds[2] = ivec3[2](
        ivec3(ijk.xy, 0),
        ivec3(ijk.xy, 1)
    );
    ivec3 upperBounds[2] = ivec3[2](
        ivec3(ijk.xy, ku_gridsize.z - 1),
        ivec3(ijk.xy, ku_gridsize.z - 0)
    );
    imageStore(nextstaggeredw,  lowerBounds[0], vec4(0));
    imageStore(nextstaggeredw,  lowerBounds[1], vec4(0));
    imageStore(nextstaggeredw,  upperBounds[0], vec4(0));
    imageStore(nextstaggeredw,  upperBounds[1], vec4(0));
    imageStore(nextstaggeredu, lowerBounds[0], 
        imageLoad(prevstaggeredu, lowerBounds[1]) 
    );
    imageStore(nextstaggeredv, lowerBounds[0], 
        imageLoad(prevstaggeredv, lowerBounds[1]) 
    );
    upperBounds[0].z -= 1;
    upperBounds[1].z -= 1;
    imageStore(nextstaggeredu, upperBounds[1], 
        imageLoad(prevstaggeredu, upperBounds[0]) 
    );
    imageStore(nextstaggeredv, upperBounds[1], 
        imageLoad(prevstaggeredv, upperBounds[0]) 
    );
    return;
}


void normalizeVelocities(ivec3 ijk)
{
    vec2 tmp[3] = vec2[3](
        imageLoad(prevstaggeredu, ijk).xy,
        imageLoad(prevstaggeredv, ijk).xy,
        imageLoad(prevstaggeredw, ijk).xy
    );
    for(int i = 0; i < 3; ++i) 
    {
        tmp[i].x = mix(
            tmp[i].x / tmp[i].y,
            0,
            float( tmp[i].y < ku_epsilon )
        );
    }


    imageStore(nextstaggeredu, ijk, vec4(tmp[0].x, 0, 0, 0));
    imageStore(nextstaggeredv, ijk, vec4(tmp[1].x, 0, 0, 0));
    imageStore(nextstaggeredw, ijk, vec4(tmp[2].x, 0, 0, 0));
    return;
}