#version 460
#extension GL_EXT_shader_image_load_formatted : enable
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout(binding = 0) readonly  uniform image3D prevstaggeredv; /* .x = vel.v, .y = interpolation weight */
layout(binding = 1) writeonly uniform image3D nextstaggeredv; /* .x = vel.v, .y = interpolation weight */


uniform float ku_dt;
uniform float ku_gravity;


void main()
{
    ivec3 workID = ivec3(gl_GlobalInvocationID);


    imageStore(nextstaggeredv, workID, 
        imageLoad(prevstaggeredv, workID) + ku_dt * ku_gravity
    );
    return;
}




