#version 460
#extension GL_EXT_shader_image_load_formatted : enable
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout(location = 0) uniform sampler3D velOldU;
layout(location = 1) uniform sampler3D velOldV;
layout(location = 2) uniform sampler3D velOldW;
layout(location = 3) uniform sampler3D velNewU;
layout(location = 4) uniform sampler3D velNewV;
layout(location = 5) uniform sampler3D velNewW;
layout(location = 6) uniform sampler3D position;
layout(location = 7) uniform sampler3D currVelocity;
layout(location = 8) writeonly uniform image3D nextVelocity;


vec3 trilerpStaggeredVelocities(
    vec3         position,
    in sampler3D velu,
    in sampler3D velv,
    in sampler3D velw
);


uniform float ku_dt;
uniform float ku_dl;
uniform float ku_flipRatio;

float k_invdl = 1.0f / ku_dl;

void main()
{
    ivec3 texelCoord = ivec3(gl_GlobalInvocationID);
    vec3  pos    = texelFetch(position, texelCoord, 0).xyz; 
    vec3 oldvel  = trilerpStaggeredVelocities(pos, velOldU, velOldV, velOldW);
    vec3 newvel  = trilerpStaggeredVelocities(pos, velNewU, velNewV, velNewW);
    vec3 currvel = texelFetch(currVelocity, texelCoord, 0).xyz;

    currvel = newvel + ku_flipRatio * (currvel - oldvel);
    imageStore(nextVelocity, texelCoord, vec4(currvel, 1.0f));
    return;
}




vec3 barycentricWeights(vec3 position)
{
    return ( position - floor(position) ) * k_invdl;
}


vec3 trilerpStaggeredVelocities(
    vec3         position,
    in sampler3D velu,
    in sampler3D velv,
    in sampler3D velw
) {
    vec3 lerpedVel = vec3(0);
    ivec3 posi = ivec3(floor(position));
    vec3 w   = barycentricWeights(position);
    vec3 omw = vec3(1.0f) - w;
    float volumeFactors[8] = float[8](
        omw.x * omw.y * omw.z, 
        w.x   * omw.y * omw.z,
        omw.x * w.y   * omw.z,
        w.x   * w.y   * omw.z,
        omw.x * omw.y * w.z,
        w.x   * omw.y * w.z,
        omw.x * w.y   * w.z,
        w.x   * w.y   * w.z
    );
    ivec3 finalIndices[8] = ivec3[8](
        posi + ivec3(0, 0, 0),
        posi + ivec3(1, 0, 0),
        posi + ivec3(0, 1, 0),
        posi + ivec3(1, 1, 0),
        posi + ivec3(0, 0, 1),
        posi + ivec3(1, 0, 1),
        posi + ivec3(0, 1, 1),
        posi + ivec3(1, 1, 1)
    );


    for(uint i = 0; i < 8; ++i) {
        lerpedVel.x += texelFetch(velu, finalIndices[i], 0).x * volumeFactors[i];
    }
    for(uint i = 0; i < 8; ++i) {
        lerpedVel.y += texelFetch(velv, finalIndices[i], 0).x * volumeFactors[i];
    }
    for(uint i = 0; i < 8; ++i) {
        lerpedVel.z += texelFetch(velw, finalIndices[i], 0).x * volumeFactors[i];
    }
    return lerpedVel;
}