#version 460
#extension GL_EXT_shader_image_load_formatted : enable
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout(location = 0) uniform sampler3D velOld;
layout(location = 1) uniform sampler3D velNew;
layout(location = 3) readonly  uniform image3D prevposition; 
layout(location = 4) writeonly uniform image3D nextposition;


uniform float ku_dt;



void main()
{
    return;
    // imageWrite()
    // imageWrite()
}