#version 460
#extension GL_EXT_shader_image_load_formatted : enable
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout(location = 0) uniform sampler3D pressure;
layout(location = 1) uniform sampler3D celltypes;
layout(location = 2) writeonly uniform image3D velu;
layout(location = 3) writeonly uniform image3D velv;
layout(location = 4) writeonly uniform image3D velw;




void main()
{
    return;
}