#version 460
layout(local_size_x =   5, local_size_y =   5, local_size_z =   5) in;
layout(binding = 0) uniform sampler3D positions;
layout(binding = 1) uniform sampler3D velocities;
layout(binding = 2) uniform sampler3D celltypes;
layout(binding = 3, rg32f)           uniform image3D prevstaggeredu; /* .x = vel.u, .y = interpolation weight */
layout(binding = 4, rg32f)           uniform image3D prevstaggeredv; /* .x = vel.v, .y = interpolation weight */
layout(binding = 5, rg32f)           uniform image3D prevstaggeredw; /* .x = vel.w, .y = interpolation weight */
layout(binding = 6, rg32f) writeonly uniform image3D nextstaggeredu; /* .x = vel.u, .y = interpolation weight */
layout(binding = 7, rg32f) writeonly uniform image3D nextstaggeredv; /* .x = vel.v, .y = interpolation weight */
layout(binding = 8, rg32f) writeonly uniform image3D nextstaggeredw; /* .x = vel.w, .y = interpolation weight */


uniform vec3  u_bottomLeftmostPosition;
uniform float ku_dl;


const float halfdl = ku_dl * 0.5f;


vec2 fetchStaggered(in image3D grid, in ivec3 coord, in bool RightTrueLeftFalse)
{
    return texelFetch(grid, coord + ivec3(0, int(RightTrueLeftFalse), 0), 0).xy;
}


vec2 fetchStaggeredQuantity(in image3D grid, in ivec3 coord, in bool RightTrueLeftFalse)
{
    return texelFetch(grid, coord + ivec3(0, int(RightTrueLeftFalse), 0), 0).x;
}


vec3 barycentricWeights(vec3 position)
{
    vec3 gridDisplacement = ( position - vec3(u_bottomLeftmostPosition) ) / ku_dl;
    ivec3 ijk = floor(gridDisplacement);
    return gridDisplacement - vec3(ijk);
}

ivec3 getIndices(vec3 position)
{
    return floor( ( position - vec3(u_bottomLeftmostPosition) ) / ku_dl );
}



// void splatCoordinate(
//     in image3D img, 
//     in vec3    position, 
//     in float   quantity
// ) {
//     /* */
// }


// void inverseInterpolateQuantityToGrid(
//     in image3D gridX,
//     in image3D gridY,
//     in image3D gridZ,
//     in vec3    position,
//     in vec3    velocity
// ) {

//     splatCoordinate(img, position, velocity);


//     return;
// }


void splatWeightedVelcitiesX(
    in image3D destination
    in vec3 position, 
    in vec3 velocity,
    in vec3 shiftOffset
) {
    vec3  shifted, w, omw;
    ivec3 shiftedi;
    float volumeFactors[8];

    /* Shift across X direction (i coordinate) */
    // shifted = vec3(
    //     position.x,
    //     position.y - halfdl,
    //     position.z - halfdl
    // );
    shifted  = position - shiftOffset;
    shiftedi = floor(shifted);
    w = barycentricWeights(shifted);
    omw = vec3(1.0f) - w;

    /* 
        Every Index i that is inc/dec gets w_i weight attached, otherwise 1-w_i
        Regardless of whether it is by 1/2 or 1 
    */
    /* the indices in comments are for illustration in the X direction */
    volumeFactors = float[8](
        /* (i, j, k) + (-0.5, 0, 0) */ omw.x * omw.y * omw.z, 
        /* (i, j, k) + (+0.5, 0, 0) */ w.x   * omw.y * omw.z,
        /* (i, j, k) + (-0.5, 1, 0) */ omw.x * w.y   * omw.z,
        /* (i, j, k) + (+0.5, 1, 0) */ w.x   * w.y   * omw.z,
        /* (i, j, k) + (-0.5, 0, 1) */ omw.x * omw.y * w.z,
        /* (i, j, k) + (+0.5, 0, 1) */ w.x   * omw.y * w.z,
        /* (i, j, k) + (-0.5, 1, 1) */ omw.x * w.y   * w.z,
        /* (i, j, k) + (+0.5, 1, 1) */ w.x   * w.y   * w.z,
    );
    imageStore(staggeredu, shiftedi + ivec3(0, 0, 0), vel.x * volumeFactors[0]);
    imageStore(staggeredu, shiftedi + ivec3(1, 0, 0), vel.x * volumeFactors[1]);
    imageStore(staggeredu, shiftedi + ivec3(0, 1, 0), vel.x * volumeFactors[2]);
    imageStore(staggeredu, shiftedi + ivec3(1, 1, 0), vel.x * volumeFactors[3]);
    imageStore(staggeredu, shiftedi + ivec3(0, 0, 1), vel.x * volumeFactors[4]);
    imageStore(staggeredu, shiftedi + ivec3(1, 0, 1), vel.x * volumeFactors[5]);
    imageStore(staggeredu, shiftedi + ivec3(0, 1, 1), vel.x * volumeFactors[6]);
    imageStore(staggeredu, shiftedi + ivec3(1, 1, 1), vel.x * volumeFactors[7]);
    return;
}


void splatWeightedVelcities(
    in image3D oldval,
    in image3D dest
    in vec3    position, 
    in float   vel,
    in vec3    shiftOffset
) {
    vec3  shifted, w, omw;
    ivec3 shiftedi;
    float volumeFactors[8];
    ivec3 finalIndices[8];

    /* Shift across a direction (i/j/k coordinate) */
    shifted  = position - shiftOffset;
    shiftedi = floor(shifted);
    w   = barycentricWeights(shifted);
    omw = vec3(1.0f) - w;

    /* 
        Every Index Q that is inc/dec gets w_q weight attached, otherwise 1-w_q
        Regardless of whether it is by 1/2 or 1 
    */
    /* the indices in comments are for illustration in the X direction */
    /* This can also apply in the y or z direction */
    volumeFactors = float[8](
        /* (i, j, k) + (-0.5, 0, 0) */ omw.x * omw.y * omw.z, 
        /* (i, j, k) + (+0.5, 0, 0) */ w.x   * omw.y * omw.z,
        /* (i, j, k) + (-0.5, 1, 0) */ omw.x * w.y   * omw.z,
        /* (i, j, k) + (+0.5, 1, 0) */ w.x   * w.y   * omw.z,
        /* (i, j, k) + (-0.5, 0, 1) */ omw.x * omw.y * w.z,
        /* (i, j, k) + (+0.5, 0, 1) */ w.x   * omw.y * w.z,
        /* (i, j, k) + (-0.5, 1, 1) */ omw.x * w.y   * w.z,
        /* (i, j, k) + (+0.5, 1, 1) */ w.x   * w.y   * w.z,
    );
    finalIndices = ivec3[8](
        shiftedi + ivec3(0, 0, 0),
        shiftedi + ivec3(1, 0, 0),
        shiftedi + ivec3(0, 1, 0),
        shiftedi + ivec3(1, 1, 0),
        shiftedi + ivec3(0, 0, 1),
        shiftedi + ivec3(1, 0, 1),
        shiftedi + ivec3(0, 1, 1),
        shiftedi + ivec3(1, 1, 1)
    )
    /*
        velocity must be multiplied by the volume factor
        that is not done here, to save time
        next compute pass is boundary conditions, and its more relevant there

        Moreover, this is incomplete because I need to:
        old = imageRead(...)
        updated = old + currently_calc_value;
        imageWrite(..., updated);
        Need to add texture ping-pong again.
    */
    
    vec2 to_write = vec2(0); 
    for(uint i = 0; i < 8; ++i) {
        to_write  = imageLoad(oldval, finalIndices[i], 0).xy;
        to_write += vec2(vel, volumeFactors[i]);
        imageStore(dest, finalIndices[i], vec4(to_write, 0, 0) );
    }
    return;
}



void main()
{
    return;
}